### ISSUE TITLE
Issue on Mac OS X with clang

### ISSUE THREAD

**Issue by jdtuck** [david-cortes/findblas#1]
On anaconda3 on Mac OS X I get the following error

`ld: library not found for -l:libmkl_rt.dylib` when using the distutil extension. The colon seems to be the issue

**Comment by jdtuck** [comment]
Sorry its not the :, but on the mac it is just not finding the library during compile. Paths are good, its the lib in front, should be `-lmkl_rt`, also `-Wl,-rpath,${MKLROOT}/lib` is the right form, should not have a `=`

**Comment by jdtuck** [comment]
Works for me, will continue to testing on my other systems. Thank you for this package it solved a need I was programming for myself. Nice work!

**Comment by jdtuck** [comment]
So now have an issue like this on anaconda on linux

`ld: cannot find -l:mkl_rt`

Ideas?

**Comment by david-cortes** [comment]
Hmm, that’s very weird. Can you post the output from
```python
import findblas
print(findblas.find_blas())
```
```python
from sys import platform
print(platform)
```

**Comment by david-cortes** [comment]
Oh actually I think it's because of this: https://github.com/david-cortes/findblas/commit/4aca4ba884326e196a60c889bf600d1fa10d47c7#diff-490df1053b28e4d9977ce8b5a0731395

Will fix now.

**Comment by jdtuck** [comment]
awesome thanks!

**Comment by david-cortes** [comment]
Fixed. Could you please confirm with version 0.1.8.1 if it works for you?

**Comment by jdtuck** [comment]
Works!
