### ISSUE TITLE
Building a package using findblas

### ISSUE THREAD

**Issue by jdtuck** [david-cortes/findblas#7]
When building a package with findblass in setup.py. If it fails to find a blas library and comes to this prompt

`Is this a BLAS library? [y/n]: n
Found file with name matching 'blas'
/usr/local/liblibopenblas64_p-r0.3.23.dev.dylib`

The build fails as no response is given. Is there a way we can make it just got through these lists or another option when its used in distutils?

**Comment by jdtuck** [comment]
Part of the issue here is that `mkl-devel` is no longer supported on the mac. So needing it to use other blas libraries on the system.

**Comment by david-cortes** [comment]
> Is there a way we can make it just got through these lists or another option when its used in distutils?

Yes, you can pass `allow_unidentified_blas=False`.

It unfortunately doesn't have support for apple's veclib from accelerate, so you'd need to have something like openblas installed if using it on an ARM variety of apple.

**Comment by jdtuck** [comment]
That does not work from your distutils

https://github.com/david-cortes/findblas/blob/fafac4ebcae00d81707bafe7711bb7a6291713fc/findblas/distutils.py#L23

As that parameter is not passed

**Comment by jdtuck** [comment]
Can we reopen the issue?

**Comment by david-cortes** [comment]
Actually, I think I misunderstood the issue - pushed a fix now which should not call it from `distutils.py`:
```shell
pip install -U findblas
```

**Comment by david-cortes** [comment]
Could you confirm that it works for you in the sense that it fails instead of prompting?

**Comment by jdtuck** [comment]
Sure

**Comment by jdtuck** [comment]
Its finding the scipy blas

`Installation: Using BLAS library found in:
      /private/var/folders/f1/72rqtvz96rx2jg5jc16s70q0002lrh/T/pip-build-env-x5giff7n/overlay/lib/python3.12/site-packages/scipy/linalg/cython_blas.cpython-312-darwin.so`

But when linking get this error

`ld: library 'cython_blas.cpython-312-darwin' not found`

**Comment by jdtuck** [comment]
Because its in the private build area when building via pip

**Comment by jdtuck** [comment]
Sort of related, but one thought, could you add support for openblas installed via homebrew on the mac. The libraries are installed here in `/usr/local/lib/`

```
-rwxr-xr-x  1 root  wheel    65M Dec 21 16:19 libopenblas64_.0.dylib
-rw-r--r--  1 root  wheel    71M Dec 21 16:19 libopenblas64_.a
-rwxr-xr-x  1 root  wheel    65M Dec 21 16:19 libopenblas64_.dylib
-rw-r--r--  1 root  wheel    71M Dec 21 16:19 libopenblas64_p-r0.3.23.dev.a
-rwxr-xr-x  1 root  wheel    65M Dec 21 16:19 libopenblas64_p-r0.3.23.dev.dylib
```

**Comment by david-cortes** [comment]
@jdtuck I've pushed a small update which should now make it look into paths from brew-managed libraries. Could you give it a try from the current master branch?

**Comment by jdtuck** [comment]
Works for me

/vr

Derek
________________________________
From: david-cortes ***@***.***>
Sent: Sunday, May 26, 2024 9:36:10 AM
To: david-cortes/findblas ***@***.***>
Cc: Tucker, J. Derek ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [david-cortes/findblas] Building a package using findblas (Issue #7)


@jdtuck<https://github.com/jdtuck> I've pushed a small update which should now make it look into paths from brew-managed libraries. Could you give it a try from the current master branch?
